Algoritmo "antecessor e sucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/01/2024
Var
n1, suc, ant: inteiro


Inicio
escreva("digite um numero: ")
leia(n1)
suc <- n1 + 1
ant <- n1 - 1
escreval("o sucessor de ",n1," é", suc)
escreva("o antecessor de ",n1," é", ant)
Fimalgoritmo