Algoritmo "calcular delta"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/01/2024
Var
a, b, c, delta: real


Inicio
escreva("digite o valor de a: ")
leia(a)
escreva("digite o valor de b: ")
leia(b)
escreva("digite o valor de c: ")
leia(c)

delta <- b*b-4*a*c
escreva("o valor de delta é ", delta)
Fimalgoritmo