Algoritmo "comtagem ate qual valor quiser"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/01/2024
Var
cont, r: inteiro


Inicio
ESCREVA("ATE QUAL VALOR DESEJA IR: ")
leia(r)
cont <- 1
repita
escreva(cont)
 cont <- cont +1
ate(cont = r +1 )
Fimalgoritmo