Algoritmo "dobro e terça parte de um numero"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/01/2024
Var
n1, dobro, terco: real
Inicio
escreva("Digite um numero: ")
leia(n1)
dobro <- n1 * 2
terco <- n1 / 3
escreval("O dobro de ",n1, " é", dobro)
escreva("O terço de ",n1," é", terco)
Fimalgoritmo