Algoritmo "parOUimpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/01/2024
Var
n1, n2: inteiro

Inicio
escreva("digite um numero: ")
leia(n2)
n1 <- n2 % 2
se(n1 = 1)entao
      escreva("o numero ", n2, " è impar")
senao
      escreva("o numero ", n2, " è par")
fimse
Fimalgoritmo