Algoritmo "podevotarounão"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/01/2024
Var
idade: inteiro


Inicio
escreva("digite sua idade: ")
leia(idade)
se(idade >- 18)entao
   escreva("voce podera votar")
senao
     escreva("voce não pode votar")
fimse
Fimalgoritmo