Algoritmo "reais em dolares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/01/2024
Var
dol, reais, valor: real


Inicio
escreva("digite quantos dolares voce tem: ")
leia(dol)
escreva("digite a cotação do dolar no dia de hoje: ")
leia(valor)
reais <- dol * valor
escreva("voce tera ",reais, " reais")
Fimalgoritmo