Algoritmo "somador entre vi-vf"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/01/2024
Var
vi, vf, r: real


Inicio
escreva("com qual numero voce deseja iniciar: ")
leia(vi)
escreva("qual sera o ultimo numero: ")
leia(vf)
r <- (vi + vf)*(vf/2)
escreva("a soma dos numero entre ",vi," e ",vf," é igual a ",r)
Fimalgoritmo