Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/01/2024
Var
n1, n2, s:inteiro


Inicio
escreva("digite o primeiro numero: ")
leia(n1)
escreva("digite o segundo numero: ")
leia(n2)
s <- n1 + n2
escreva("a soma entre", n1, " e", n2 ," é igual a", s )
Fimalgoritmo